.TH VPNCMD4 1 "May 2026" "SoftEther VPN"
.SH NAME
vpncmd4 \- SoftEther VPN command-line management tool (for SoftEther VPN Stable)
.SH SYNOPSIS
.B vpncmd4
[host] [/SERVER|/CLIENT] [/CMD command]
.SH DESCRIPTION
vpncmd4 (vpncmd for SoftEther VPN Stable) is the command-line administration tool for SoftEther VPN.
It can manage VPN Server, VPN Bridge, and VPN Client instances.

For full documentation, see:
https://www.softether.org/

.SH EXAMPLES
vpncmd4 localhost /SERVER
vpncmd4 localhost /CLIENT /CMD NicCreate testnic

.SH SEE ALSO
SoftEther VPN Project documentation:
https://www.softether.org/
